### ISSUE TITLE
ERROR in Conflict: Multiple assets emit different content to the same filename index.html

### ISSUE THREAD

**Issue by beilo** [xn-sakina/xn#3]
Failed to compile.

Conflict: Multiple assets emit different content to the same filename index.html
ERROR in Conflict: Multiple assets emit different content to the same filename index.html

[public.zip](https://github.com/xn-sakina/xn/files/10915067/public.zip)

Now using node v16.15.1

**Comment by fz6m** [comment]
这个复现我本地是正常的，没有问题。

**Comment by beilo** [comment]
会是win的原因嘛？我应该怎么样看详细的报错信息，用来排查问题？

**Comment by fz6m** [comment]
应该是 win 路径的问题，将在最新版本中修复。
